name: far_pytorch_v1
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py39hdda0065_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.26.0=py39h5f9d8c6_0
  - numpy-base=1.26.0=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.11=h7f8727e_2
  - pillow=9.4.0=py39h6a678d5_1
  - pip=23.2.1=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - pytorch=1.12.1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu102
  - torchvision=0.13.1=py39_cu102
  - typing_extensions=4.7.1=py39h06a4308_0
  - urllib3=1.26.16=py39h06a4308_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==2.0.0
    - accelerate==0.21.0
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - albumentations==1.3.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - cachetools==5.3.2
    - cmake==3.27.6
    - contourpy==1.1.1
    - cycler==0.12.1
    - einops==0.7.0
    - filelock==3.12.4
    - fonttools==4.43.1
    - frozenlist==1.4.0
    - fsspec==2023.10.0
    - future==0.18.3
    - google-auth==2.23.3
    - google-auth-oauthlib==1.1.0
    - grpcio==1.59.2
    - h5py==3.10.0
    - imageio==2.31.3
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.0
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - kornia==0.7.1
    - lazy-loader==0.3
    - lightning-utilities==0.9.0
    - lit==17.0.2
    - loguru==0.7.2
    - markdown==3.5
    - markupsafe==2.1.3
    - matplotlib==3.8.0
    - multidict==6.0.4
    - networkx==3.2.1
    - numpy-quaternion==2022.4.3
    - oauthlib==3.2.2
    - opencv-python==4.8.1.78
    - opencv-python-headless==4.8.1.78
    - packaging==23.1
    - pandas==2.1.2
    - protobuf==4.23.4
    - psutil==5.9.5
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydegensac==0.1.2
    - pydeprecate==0.3.0
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytorch-lightning==1.3.5
    - pytz==2023.3.post1
    - pyyaml==5.4.1
    - quaternion==3.5.2.post4
    - qudida==0.0.4
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.22.0
    - scikit-learn==1.3.2
    - scipy==1.11.3
    - six==1.16.0
    - tensorboard==2.15.0
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.2.0
    - tifffile==2023.9.26
    - torchmetrics==0.6.0
    - tqdm==4.66.1
    - transforms3d==0.4.1
    - triton==2.0.0
    - tzdata==2023.3
    - werkzeug==3.0.1
    - yacs==0.1.8
    - yarl==1.9.2
    - zipp==3.17.0
